##### PREFIX #################################################

unbind C-b

# Emcas compatible prefix
set -g prefix C-Space
bind C-Space send-prefix


##### PERFORMANCE ###########################################

set -sg escape-time 0
set -g history-limit 100000

# True color
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"


##### INDEX ##################################################

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on


##### PANE & WINDOW #########################################

# Splitler
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind o select-pane -t :.+
bind p select-pane -t :.-
bind O rotate-window -D
bind P rotate-window -U

# Resize
bind -r < resize-pane -L 5
bind -r > resize-pane -R 5
bind -r + resize-pane -U 5
bind -r _ resize-pane -D 5


##### COPY MODE (EMACS STYLE) ################################


setw -g mode-keys emacs

bind c copy-mode


set -g mouse on
unbind -T copy-mode MouseDragEnd1Pane
bind -T copy-mode MouseDragEnd1Pane send -X copy-selection-and-cancel


##### STATUS BAR ############################################

set -g status-position bottom
set -g status-interval 2

set -g status-style "bg=colour235,fg=colour248"
set -g status-left " #[fg=colour39]#S #[default]"
set -g status-right "#[fg=colour245]%Y-%m-%d #[fg=colour39]%H:%M "

setw -g window-status-current-format "#[bg=colour39,fg=colour235] #I:#W "
setw -g window-status-format "#[fg=colour245] #I:#W "


##### QUALITY OF LIFE #######################################


bind n new-window -c "#{pane_current_path}"

# Reload
bind r source-file ~/.tmux.conf \; display "tmux.conf reloaded"


bind x kill-pane
