// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1776539278);
user_pref("app.update.lastUpdateTime.background-update-timer", 1776587532);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1776539278);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1776539163);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.startup.homepage_override.buildID", "20260317093326");
user_pref("browser.startup.homepage_override.mstone", "140.9.0");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.lastAppBuildId", "20260410162305");
user_pref("extensions.lastAppVersion", "9.0");
user_pref("extensions.lastPlatformVersion", "140.9.0");
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.zotero.baseAttachmentPath", "/opt/zotero-data");
user_pref("extensions.zotero.dataDir", "/opt/zotero-data");
user_pref("extensions.zotero.export.bibliographySettings", "{\"mode\":\"bibliography\",\"method\":\"copy-to-clipboard\"}");
user_pref("extensions.zotero.export.lastLocale", "en-US");
user_pref("extensions.zotero.export.lastStyle", "http://www.zotero.org/styles/ieee");
user_pref("extensions.zotero.firstRun.skipFirefoxProfileAccessCheck", true);
user_pref("extensions.zotero.firstRun2", false);
user_pref("extensions.zotero.ignoreLegacyDataDir.auto", true);
user_pref("extensions.zotero.lastSelectedPrefPane", "zotero-prefpane-advanced");
user_pref("extensions.zotero.lastViewedFolder", "L1");
user_pref("extensions.zotero.pane.persist", "{\"zotero-reader-sidebar-pane\":{\"collapsed\":\"true\"},\"zotero-layout-switcher\":{\"orient\":\"horizontal\"},\"zotero-items-splitter\":{\"orient\":\"horizontal\"},\"zotero-item-pane\":{\"width\":\"337\",\"height\":\"205\"},\"zotero-context-splitter\":{\"state\":\"collapsed\"},\"zotero-context-splitter-stacked\":{\"state\":\"collapsed\"}}");
user_pref("extensions.zotero.panes.abstract.open", true);
user_pref("extensions.zotero.panes.attachment-annotations.open", true);
user_pref("extensions.zotero.panes.attachment-info.open", true);
user_pref("extensions.zotero.panes.attachments.open", true);
user_pref("extensions.zotero.panes.context-all-notes.open", true);
user_pref("extensions.zotero.panes.context-item-notes.open", true);
user_pref("extensions.zotero.panes.info.open", true);
user_pref("extensions.zotero.panes.libraries-collections.open", true);
user_pref("extensions.zotero.panes.note-info.open", true);
user_pref("extensions.zotero.panes.notes.open", true);
user_pref("extensions.zotero.panes.related.open", true);
user_pref("extensions.zotero.panes.tags.open", true);
user_pref("extensions.zotero.prefVersion", 21);
user_pref("extensions.zotero.recentSaveTargets", "[{\"id\":\"L1\",\"sessionID\":\"hVBkjWXb\"}]");
user_pref("extensions.zotero.saveRelativeAttachmentPath", true);
user_pref("extensions.zotero.sidebarState", "{\"library\":{\"width\":240,\"open\":false},\"reader\":{\"width\":240,\"open\":false}}");
user_pref("extensions.zotero.useDataDir", true);
user_pref("extensions.zoteroOpenOfficeIntegration.lastAttemptedVersion", "9.0.0.SOURCE");
user_pref("extensions.zoteroOpenOfficeIntegration.unopkgPaths", "{\"/usr/bin/unopkg\":true,\"/usr/lib64/libreoffice/program/unopkg\":true}");
user_pref("extensions.zoteroOpenOfficeIntegration.version", "9.0.0.SOURCE");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("intl.accept_languages", "en-US, en");
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
